### ISSUE TITLE
What Type Of Ide i Can Use Whit OBEngine?

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [Sygmei/ObEngine#151]
title

**Comment by Sygmei** [comment]
I personally use Visual Studio Code to edit the Lua files but you could use any text editor.
Try to choose an editor with Lua Syntax Highlighting and maybe a linter / autocompletion features.
You could go with VS Code, Atom, Notepad++, Sublime Text etc...

**Comment by xXxToxicBlueDustxXx** [comment]
have you use this ide? [https://studio.zerobrane.com/](ZeroBrane Studio)

### Feature highlights

- > Small, portable, open-source, and cross-platform (Windows, macOS, and Linux);
- > Auto-completion for functions, keywords, and custom APIs;
- > Syntax highlighting and folding for 110+ languages and file formats;
- > Project view with auto-refresh and ability to hide files and directories from the list;
- > Interactive console to test Lua code snippets with local and remote execution;
- > Integrated debugger with support for local and remote debugging, including cross-platform and on-device debugging;
- > Live coding with Lua, LÖVE, Gideros, Moai, Corona, GSL-Shell and other Lua engines;
- > Multi-language support with translations to French, Spanish, Russian, German, Chinese, Esperanto, Italian, Bulgarian, and Brazilian Portuguese languages and documentation to add your own;
- > 50+ extension packages in the package repository;
- > Fuzzy search for files, symbols, and library functions, function outline, and more.

also is open source so you can make a fork of that ide for OBenine :)

**Comment by Sygmei** [comment]
Nice ! I'll take a look, thanks :)

**Comment by xXxToxicBlueDustxXx** [comment]
no problem :)
