### ISSUE TITLE
Link to Lua documentation gets permission error

### ISSUE THREAD

**Issue by ryanford-frontend** [Sygmei/ObEngine#169]
When trying to navigate to the Lua docs from the website https://obengine.io/doc.html gets a 403 permission error.

**Comment by Sygmei** [comment]
Yes ! Thanks for the report, I'm working on the new Lua doc as we are speaking, it should be available soon. There are some broken links in the wiki too. I'll put a placeholder for now

**Comment by Sygmei** [comment]
Okay, it should be fixed, I removed all broken links from the wiki and the Lua documentation now shows "Not available"
