### ISSUE TITLE
Build failed with MinGW64

### ISSUE THREAD

**Issue by mjopenglsdl** [Sygmei/ObEngine#180]
D:/devel/msys64/home/minjie/git_repo/ObEngine/extlibs/dynamicLinker/include/dynamicLinker/dynamicLinker.hpp:75:32: error: **invalid conversion from 'FARPROC' {aka 'long long int (*)()'} to 'void*' [-fpermissive]**
   75 |           return GetProcAddress( (HINSTANCE) parent->lib->ptr() , name.c_str() );
      |                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                FARPROC {aka long long int (*)()}

As mentioned in this post:
[https://stackoverflow.com/questions/13958081/mingw-compile-error-invalid-conversion-from-farproc-to-void-but-msvc-com](https://stackoverflow.com/questions/13958081/mingw-compile-error-invalid-conversion-from-farproc-to-void-but-msvc-com)

**Comment by Sygmei** [comment]
Interesting ! dynamicLinker is a bundled dependency and the repository is here : https://github.com/Marqin/dynamicLinker
I should make a flag that allows you to enable / disable plugins but this seems to be fixable easily

**Comment by Sygmei** [comment]
The last commit should fix your issue :) https://github.com/Sygmei/ObEngine/commit/bc93e87bbc56369a35c7b9ed621a4c4c690407f3
Thanks for reporting the problem !

**Comment by mjopenglsdl** [comment]
It now works perfectly with MinGW, many thanks !
