### ISSUE TITLE
Fix Linux build on Azure Pipelines

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#185]
You can check what I tried to do here : https://github.com/Sygmei/ObEngine/blob/58415887184aad2947962fece8958e01e4edbe93/azure-pipelines.yml

**Comment by Sygmei** [comment]
Since the main build jobs are running on GitHub actions now, no need to spend too much time on this

**Comment by AugustasV** [comment]
Cool I will try to fix this issue!
