### ISSUE TITLE
Make ÖbEngine dev installation easier

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#202]
Installing ÖbEngine as a developer is not easy. You have to clone the repository, build the project with CMake and compile it.
That part is fine but there is a few extra steps that could be automated :
- Copying SFML dlls (Windows only)
- Copying engine/ directory
- Symlink Data/ Lib/ and Sprites/ folder from git folder to execution folder
- Change execution folder for some IDEs to the newly copied folder

**Comment by marcotaranta** [comment]
Hello! Can I help with that issue?

**Comment by Sygmei** [comment]
Sure :) If you have any questions don't hesitate to join the Discord server (link on readme).

**Comment by Sygmei** [comment]
Done in https://github.com/Sygmei/ObEngine/commit/83045a280e8ef0f881fe04f99cb1d66e48c25ead
