### ISSUE TITLE
While the editor menu is open you shouldn't be able to zoom or create colliders

### ISSUE THREAD

**Issue by Tzupy** [Sygmei/ObEngine#206]
After opening the Editor Menu, the camera can be zoomed while scrolling the mouse wheel anywhere on the screen.

When changing to Collisions mode while the menu is still open, right clicking on the screen will create colliders. This also happens when right clicking on the open dropdown list while in Collisions mode with the editor window closed.

**Comment by Tzupy** [comment]
After opening the Editor Menu, the camera can be zoomed while scrolling the mouse wheel anywhere on the screen.

When changing to Collisions mode while the menu is still open, right clicking on the screen will create colliders.

**Comment by Sygmei** [comment]
Since the Editor has been dropped, the issue has also disappeared, I'll close it for now and reopen it if the issue reappears with the new editor (which I hope won't).
