### ISSUE TITLE
Make getAllGameObjects() binding directly return the gameObjects table

### ISSUE THREAD

**Issue by Darnagof** [Sygmei/ObEngine#291]
`Scene.getAllGameObjects()` binding should return directly the exposition table of the object (so no need to do `access()`), just like `Scene.getGameObject()`.

**Comment by Sygmei** [comment]
Yup !
To do that we only have to create a new method inside [Core/Scene/Scene.hpp](https://github.com/Sygmei/ObEngine/blob/master/include/Core/Scene/Scene.hpp) and [Core/Scene/Scene.cpp](https://github.com/Sygmei/ObEngine/blob/master/src/Core/Scene/Scene.cpp) named `sceneGetAllGameObjectsProxy` flagged with the following [Obidog](https://github.com/ObEngine/Obidog) tag : `\proxy{obe::Scene::Scene::getAllGameObjects}`.
Of course we need to run `obidog bindings` after that to regenerate the bindings.
