### ISSUE TITLE
Remove InputActionEvent

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#321]
Remove the `InputActionEvent` class since it has been replaced by an [`Event`](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Input/InputAction.cpp#L79).
This issue should be done on the [v0.5](https://github.com/Sygmei/ObEngine/tree/v0.5) branch since it contains the Event rework.

## Places to look at : 
- [`InputActionEvent` header](https://github.com/Sygmei/ObEngine/blob/v0.5/include/Core/Input/InputActionEvent.hpp)
- [`InputActionEvent` source](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Input/InputActionEvent.cpp)
- [`InputActionEvent` bindings (source)](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Bindings/obe/Input/Input.cpp#L74)
- [`InputActionEvent` bindings (header)](https://github.com/Sygmei/ObEngine/blob/v0.5/include/Core/Bindings/obe/Input/Input.hpp#L10)
- [Bindings index](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Bindings/index.cpp#L260)
- [Usage in `InputAction`](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Input/InputAction.cpp#L74)

**Comment by BeardedVagabond** [comment]
Correct me if I'm wrong, but is this literally just a code clean to remove `InputActionEvent`? Or are there places where implementation needs to be refactored to use `Event`?

**Comment by Sygmei** [comment]
@BeardedVagabond you're right :) We just need to remove InputActionEvent and its multiple references. The only place that used it (InputAction) already [triggers an Event](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Input/InputAction.cpp#L78).
Something worth checking though is this [piece of code](https://github.com/Sygmei/ObEngine/blob/v0.5/src/Core/Input/InputAction.cpp#L90), an InputActionEvent is created but there is no new Event to replace it (should it replace it anyway ?).

**Comment by BeardedVagabond** [comment]
I can take a look if you'd like. I'm interested in potentially contributing more once I'm more familiar with the engine, but this is a nice and simple warm-up :)

**Comment by Sygmei** [comment]
@BeardedVagabond this issue is all yours ! You should join the [Discord](https://discordapp.com/invite/HkM6zdT) server for more in-depth discussion about the project if you want 😄
