### ISSUE TITLE
Provide flip method for Sprite

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#413]
Sprite should have a method to flip its texture (horizontal, vertical, both). 

Some questions :
- Should the method be on Sprite (equivalent of `sprite.scale(-1,-1)`) ? 
- Should the method be on Texture ?
- Both ? (Best option imho)

**Comment by lukefelsberg** [comment]
I am interested

**Comment by Sygmei** [comment]
Sure @lukefelsberg let me know if you have any questions
Don't hesitate to join the Discord server if you need some help in setting things up :)

**Comment by lukefelsberg** [comment]
thank you sir

**Comment by DarthData410** [comment]
Hey @Sygmei is this still an open issue? At first it seemed like it was getting resolved, but then the PR seemed to have stalled. With that, do let me know...

**Comment by Sygmei** [comment]
You're right, the PR author did not respond to the comments !

Feel free to take the task, that would be great :)

**Comment by DarthData410** [comment]
Hey @Sygmei there is already a flip method for sprite. It is not using an enum, as discussed in pr #421 however it uses boolean values for flip horizontal and vertical. https://github.com/ObEngine/ObEngine/blob/f83636ba22d3dd21753658b3a2dee845023610fd/include/Core/Graphics/Sprite.hpp#L213 and for the cpp: https://github.com/ObEngine/ObEngine/blob/f83636ba22d3dd21753658b3a2dee845023610fd/src/Core/Graphics/Sprite.cpp#LL146C9-L146C9

I checked the texture and there is not a flip function for that entity. Please review and see if there is anything that truly needs to be completed on this.

**Comment by Sygmei** [comment]
Oops, you're totally right, I implemented this in ec3c0bfa66419ba81020f23ea2e19d2a037e73d6 and forgot to update the status, my bad !

Thanks for the tip
