### ISSUE TITLE
Create a proxy function for Engine::get_arguments

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#441]
This should automatically convert the `vili::node` to a `sol::lua_value` and be exposed as `Engine.Args` (like other Engine managers are)

Instead of
```lua
local args = vili.to_lua(Engine:get_arguments());
print(args.disable_vsync);
```
We could do
```lua
print(Engine.Args.disable_vsync);
```

**Comment by Sygmei** [comment]
Example on how to write a proxy function :
https://github.com/ObEngine/ObEngine/blob/v0.5/include/Core/Scene/Scene.hpp#L334

Example on how to rename an exposed field + make it into a property :
https://github.com/ObEngine/ObEngine/blob/v0.5/include/Core/Scene/Scene.hpp#L334

**Comment by DarthData410** [comment]
Hey I was browsing around new projects to get involved with and saw a nice introduction issue to resolve here. I can take this and complete it I believe. It seems straight forward, so will look to put together a PR shortly.

**Comment by Sygmei** [comment]
Great :) Don't hesitate if you have any questions

You can either ask here or join the Discord (see README)

**Comment by DarthData410** [comment]
I forked the project and cloned the repo on my main Ubuntu laptop. The build completes using cmake, but it generates a lot of files, not just "out" or compiled .bin. I noticed for your Linux section of README on the build that is still under development. Of course I can ignore the generated files, (.gitignore), anyway just getting the environment setup so can write, sync and create a PR smoothly and wanted to see if there was anything missing that is known, critical and not Yet part of the README docs for linux?

**Comment by Sygmei** [comment]
The usual way to build on Linux is the following one :
- Clone repository
- Create a `build` directory (which is excluded in the [`.gitignore`](https://github.com/ObEngine/ObEngine/blob/v0.5/.gitignore#L3) file)
- `cd` in the `build/` directory and run your `cmake` command : `cmake <FLAGS> ..`
- Then, still in the `build/` directory, run `make`

**Comment by DarthData410** [comment]
Ok that works great. Now that I can proceed successfully I will get this done, and get a PR together, and go from there.

**Comment by DarthData410** [comment]
@Sygmei So further build questions here, just getting everything lined up. It seems I have a configuration issue, build runs fine as per:

> [  1%] Built target catch
> [  2%] Built target fmt
> [  5%] Built target spdlog
> [ 15%] Built target lua
> [ 16%] Built target platformfolders
> [ 16%] Built target dynamicLinker
> [ 18%] Built target vili
> [ 18%] Built target vili-d8
> [ 19%] Built target vili-msgpack
> [ 33%] Built target Soloud
> [ 41%] Built target lunasvg
> [ 48%] Built target minizip
> [ 49%] Built target elzip
> [ 50%] Built target sfe
> [ 51%] Built target whereami
> -- Configure Git variables for ÖbEngine
> git version 2.34.1
> -- ÖbEngine Git version : v0.5:ceeace9efa521ec6dee674548053cb0bda4b9176
> -- ÖbEngine version : v0.4.2
> [ 51%] Built target ConfigureObEngineGit
> [ 99%] Built target ObEngineCore
> [100%] Built target ObEnginePlayer
> [100%] Built target obey
> 

Yet upon execution of a binary file compiled out, like obey, for example I get the following:

> /repos/ObEngine/build/src/Toolkit$ ./obey
> [12:21:17.496]<warning> : [MountablePath] Can't Mount the same path twice: MountablePath(prefix=, path=/home/bradon/Desktop/OtherProjects/repos/ObEngine/build/src/Toolkit, priority=1, implicit=true)
> [12:21:17.496]<error> : The following error occurred while running obey
> [12:21:17.496]<error> : filesystem error: cannot make canonical path: No such file or directory [/home/bradon/Desktop/OtherProjects/repos/ObEngine/build/src/Toolkit/Lib/Extlibs]
> 

Thought I would post to see if this is a quick known. As part of this effort I am doing here in working / building on Linux I am also more than happy to compile these notes so the build for linux details can be updated.

**Comment by DarthData410** [comment]
Ok so I figured out the issue here, after the build you have to move the following files, from ./build/*.*:

- libObEngineCore.a
- ObEnginePlayer
- obey

to the ../ObEngine/engine/ folder and execute, for example ObEnginePlayer, which renders **'Hello World"**

For the output of CMake + make for linux, the above seem to be the only three. The documentation talks about the toolkit as the next step for creating a project, but I can build, execute, etc. with the ObEnginePlayer rendering hello world.

**Comment by DarthData410** [comment]
@Sygmei I created a PR with what I believe you are looking for, clean compile - though I expect there will need to be changes... I wanted to get to a good starting point however, and with having a clean compile after updating the Engine.hpp/.cpp files. When you get a chance to review do let me know. I will continue to dive in...

**Comment by DarthData410** [comment]
Yeah... I would like your feedback but that is not going to work really... I'm working on an update for the code now, compiling... whats confusing a bit is having this as proxy and property. I'm building this out as a property first, and then see what feedback you might have.

**Comment by Sygmei** [comment]
Thanks for your first contribution 🥳 

If you want to be able to test your code, you'll need to use Öbidog (which is the tool used to generate Lua bindings)

Here's how to setup Öbidog : 
- Clone Öbidog's repository : `git clone https://github.com/ObEngine/Obidog.git`
- Install Python (Higher than 3.8 IIRC) : https://www.python.org/downloads/
- Open a terminal in the cloned directory and install the Python package : `pip install -e .` (make sure Python / pip are in your $PATH)
- Install Doxygen >= 1.18.18 : https://www.doxygen.nl/download.html and add it to your $PATH
- Install clang-format (through LLVM) : https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0 and add it to your $PATH
- Make sure the current working directory is Öbidog repository (not ÖbEngine) and run the bindings generator `OBENGINE_GIT_DIRECTORY="path/to/obengine/repository" obidog bindings`

**Comment by DarthData410** [comment]
Perfect! And I did find the binding finally in src/code/Bindings/obe/engine/Engine.cpp which is generated, however I see now how the bindings are created. I will follow through now with the rest of the code / test using Obidog. I'm looking forward to contributing and working with the engine in general.

**Comment by DarthData410** [comment]
Ok @Sygmei I am getting closer here, there is still some lingering issue though. I have walked through all of what you have listed above and Obidog is running - and it goes through its generation process when it hits the following:

<...lot more lines before here...>

> INFO:obidog.logger:Generating bindings for namespace obe::component
> INFO:obidog.logger:  Generating bindings for class obe::component::ComponentBase
> INFO:obidog.logger:Generating bindings for namespace obe::config
> INFO:obidog.logger:  Generating bindings for class obe::config::ConfigurationManager
> INFO:obidog.logger:  Generating bindings for class obe::config::Version
> Traceback (most recent call last):
>   File "/home/bradon/.local/bin/obidog", line 33, in <module>
>     sys.exit(load_entry_point('obidog', 'console_scripts', 'obidog')())
>   File "/home/bradon/Desktop/OtherProjects/repos/Obidog/obidog/main.py", line 46, in main
>     generate_bindings(cpp_db)
>   File "/home/bradon/Desktop/OtherProjects/repos/Obidog/obidog/bindings/generator.py", line 531, in generate_bindings
>     apply_proxies(cpp_db, namespace.functions)
>   File "/home/bradon/Desktop/OtherProjects/repos/Obidog/obidog/bindings/generator.py", line 393, in apply_proxies
>     patch.definition = function_value.definition
> AttributeError: 'NoneType' object has no attribute 'definition'
> 

Now I have backed out my changes and I am executing this on the base, forked, repo location. I can see that it is running because it is touching a lot of files - until it fails out at the same point every time. 

Any idea's from what you see here?

**Comment by Sygmei** [comment]
I think it's because on the proxy flag, you gave the following value :
`obe::engine::Engine::get_args` when the actual function name is `obe::engine::Engine::get_arguments`
https://github.com/ObEngine/ObEngine/blob/0b00ba14fba35e32c84d29858ccc4c6643c65fbc/include/Core/Engine/Engine.hpp#L165

**Comment by DarthData410** [comment]
When I completely remove the code I added, and run the Obidog bindings generation I get the same thing, at the same point. So this is taking place in binding gen with Obidog, without any changes I have made. 

I am on Ubuntu 22.04 and have installed all the requirements... I can see a good amount of files being touched by the process TBH. The bindings generator executing and then stops at that same point...

**Comment by Sygmei** [comment]
There are some issues with Obidog on my side as well, it seems a recent version of Doxygen broke backward compatibility

What I suggest is creating the binding yourself, you can take inspiration of how it was done for Scene proxies

Either way, I'll fix Obidog and try to integrate directly in the PR process so devs don't have to set it up

**Comment by Sygmei** [comment]
There are some issues with Obidog on my side as well, it seems a recent version of Doxygen broke backward compatibility

What I suggest is creating the binding yourself, you can take inspiration of how it was done for Scene proxies

Either way, I'll fix Obidog and try to integrate directly in the PR process so devs don't have to set it up

**Comment by DarthData410** [comment]
I have been walking through the LuaBridge project, and also the bindings. I feel confident I can just manually create them, follow the naming conventions, etc. Sounds good on the update, and understood on the impact of the Doxygen version changes. I will update the PR when I get this tested out, with bindings included.

**Comment by DarthData410** [comment]
Alright so I am using the hello world lua script to test out the proxy, as a property with the manually created bindings. Test lua script:
```lua
function Event.Game.Render()
    SampleObject.components.Sprite:set_texture(_canvas:render());

    local args = vili.to_lua(Engine:get_arguments());
    print(" *** -args test- *** ")
    print(args)
    print("   vs. ")
    print(Engine.Args)
    print(" *** -args test- *** ")
end
```
With the following output:

> 
>  *** -args test- *** 
> table: 0x55cb020f59d0
>    vs. 
> table: 0x55cb0213be50
>  *** -args test- *** 

I am going to sync my updates now to the existing PR, so they can be reviewed. Let me know if you have any questions. Looking forward to working with ObE !

**Comment by DarthData410** [comment]
Final test here, I used the following lua script to test the passing in of the disable_vsync example you have.:
```lua
function Event.Game.Render()
    SampleObject.components.Sprite:set_texture(_canvas:render());
    print(" *** disable_vsync test *** ")
    print(Engine.Args.disable_vsync);
end
```

And when I execute the engine with the following:

> ./ObEnginePlayer --disable_vsync true

I get the Engine.Args.disable_vsync value as desired:

>  *** disable_vsync test *** 
> true
>

**Comment by Sygmei** [comment]
Done in #448
