### ISSUE TITLE
Wrong Discord link in CONTRIBUTING file

### ISSUE THREAD

**Issue by sreramk** [Sygmei/ObEngine#88]
Hi, I would like to contribute to your ObEngine project, but I can't find any ways of contacting you. The  Discord invitation link you have included (https://discord.gg/D6JvZzM) in the "contributing" instructions section has expired.

**Comment by Sygmei** [comment]
Yeah, sadly Github doesn't have any messaging features :(
You can add me on Discord : Sygmei#9480
I'll also put back a correct Discord link on the CONTRIBUTING file !

**Comment by Sygmei** [comment]
Fixed in https://github.com/Sygmei/ObEngine/commit/d90bf9415cece7709ae5d6a26221c6fb85838bd9
